# Generated by Django 3.2.4 on 2021-06-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_rename_assigneddoctor_patient_assigneddoctorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='doctor', max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='patient', max_length=40),
        ),
    ]
